#!/bin/bash
# AF_XDP Setup Script for Oxidize
# Configures the system for high-performance AF_XDP networking
#
# Requirements:
# - Linux kernel 5.4+ (for stable AF_XDP support)
# - Root privileges
# - Network interface with XDP support

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check root
if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root"
    exit 1
fi

# Check kernel version
KERNEL_VERSION=$(uname -r | cut -d. -f1-2)
KERNEL_MAJOR=$(echo $KERNEL_VERSION | cut -d. -f1)
KERNEL_MINOR=$(echo $KERNEL_VERSION | cut -d. -f2)

if [[ $KERNEL_MAJOR -lt 5 ]] || [[ $KERNEL_MAJOR -eq 5 && $KERNEL_MINOR -lt 4 ]]; then
    log_error "Kernel version $KERNEL_VERSION is too old. AF_XDP requires Linux 5.4+"
    exit 1
fi

log_info "Kernel version $KERNEL_VERSION is compatible with AF_XDP"

# Install dependencies
log_info "Installing dependencies..."
apt-get update -qq
apt-get install -y -qq \
    build-essential \
    clang \
    llvm \
    libelf-dev \
    libbpf-dev \
    linux-headers-$(uname -r) \
    iproute2 \
    ethtool \
    2>/dev/null || true

# Configure hugepages (optional but recommended for performance)
log_info "Configuring hugepages..."
HUGEPAGES_COUNT=${HUGEPAGES_COUNT:-1024}  # Default 2GB (1024 x 2MB pages)

# Check if hugepages already configured
CURRENT_HUGEPAGES=$(cat /proc/sys/vm/nr_hugepages)
if [[ $CURRENT_HUGEPAGES -lt $HUGEPAGES_COUNT ]]; then
    echo $HUGEPAGES_COUNT > /proc/sys/vm/nr_hugepages
    
    # Make persistent
    if ! grep -q "vm.nr_hugepages" /etc/sysctl.conf; then
        echo "vm.nr_hugepages = $HUGEPAGES_COUNT" >> /etc/sysctl.conf
    fi
    log_info "Configured $HUGEPAGES_COUNT hugepages"
else
    log_info "Hugepages already configured: $CURRENT_HUGEPAGES"
fi

# Increase max locked memory for AF_XDP
log_info "Configuring memory limits..."
if ! grep -q "memlock" /etc/security/limits.conf; then
    cat >> /etc/security/limits.conf << EOF
# AF_XDP requires large locked memory regions
* soft memlock unlimited
* hard memlock unlimited
root soft memlock unlimited
root hard memlock unlimited
EOF
    log_info "Updated memory lock limits"
fi

# Enable BPF JIT
log_info "Enabling BPF JIT compiler..."
echo 1 > /proc/sys/net/core/bpf_jit_enable
if ! grep -q "net.core.bpf_jit_enable" /etc/sysctl.conf; then
    echo "net.core.bpf_jit_enable = 1" >> /etc/sysctl.conf
fi

# Increase network buffer sizes
log_info "Tuning network buffers..."
sysctl -w net.core.rmem_max=26214400 >/dev/null
sysctl -w net.core.wmem_max=26214400 >/dev/null
sysctl -w net.core.rmem_default=1048576 >/dev/null
sysctl -w net.core.wmem_default=1048576 >/dev/null
sysctl -w net.core.netdev_max_backlog=50000 >/dev/null

# Make persistent
cat >> /etc/sysctl.d/99-oxidize-xdp.conf << 'EOF'
# Oxidize AF_XDP Performance Tuning
net.core.rmem_max = 26214400
net.core.wmem_max = 26214400
net.core.rmem_default = 1048576
net.core.wmem_default = 1048576
net.core.netdev_max_backlog = 50000
net.core.bpf_jit_enable = 1
EOF

# Detect network interface for XDP
log_info "Detecting network interfaces..."
DEFAULT_IF=$(ip route | grep default | awk '{print $5}' | head -1)

if [[ -n "$DEFAULT_IF" ]]; then
    # Check XDP support
    if ethtool -i $DEFAULT_IF 2>/dev/null | grep -q "driver"; then
        DRIVER=$(ethtool -i $DEFAULT_IF | grep "driver" | awk '{print $2}')
        log_info "Default interface: $DEFAULT_IF (driver: $DRIVER)"
        
        # Check for XDP-capable drivers
        XDP_DRIVERS="i40e ixgbe mlx5_core mlx4_en nfp bnxt_en virtio_net veth igb e1000e"
        if echo "$XDP_DRIVERS" | grep -qw "$DRIVER"; then
            log_info "✓ Driver $DRIVER supports native XDP mode"
        else
            log_warn "Driver $DRIVER may only support generic XDP mode (slower)"
        fi
    fi
else
    log_warn "Could not detect default network interface"
fi

# Create oxidize config directory
mkdir -p /etc/oxidize

# Save XDP configuration
cat > /etc/oxidize/xdp-config.env << EOF
# AF_XDP Configuration
# Generated by setup-xdp.sh on $(date)

# Network interface for XDP
XDP_INTERFACE=${DEFAULT_IF:-eth0}

# XDP attach mode: native, generic, or offload
XDP_MODE=native

# Number of RX/TX queues
XDP_QUEUES=4

# Frame size for UMEM
XDP_FRAME_SIZE=4096

# Number of frames in UMEM
XDP_FRAME_COUNT=4096

# Batch size for packet processing
XDP_BATCH_SIZE=64

# Enable zero-copy mode (requires driver support)
XDP_ZERO_COPY=true

# Hugepages configured
HUGEPAGES=$HUGEPAGES_COUNT
EOF

log_info "XDP configuration saved to /etc/oxidize/xdp-config.env"

# Print summary
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  AF_XDP Setup Complete"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "  Kernel:        $(uname -r)"
echo "  Hugepages:     $HUGEPAGES_COUNT x 2MB = $((HUGEPAGES_COUNT * 2))MB"
echo "  Interface:     ${DEFAULT_IF:-eth0}"
echo "  BPF JIT:       Enabled"
echo ""
echo "  Configuration: /etc/oxidize/xdp-config.env"
echo ""
echo "  Next steps:"
echo "    1. Reboot if this is the first time running this script"
echo "    2. Run: sudo ./scripts/latitude/latitude-deploy.sh"
echo ""
echo "═══════════════════════════════════════════════════════════"

log_info "AF_XDP setup complete!"
